testng_hw
kislayao/AQA_TMS_Auto pull request #1
Opened 2023-06-24 15:29 UTC by kislayao

2023-06-26 15:04 UTC, wildpioneer requested changes

2023-06-26 15:04 UTC, wildpioneer commented on src/test/java/CalculatorTest_Div_Int.java
> +    @Test (groups = "smoke", dataProvider = "Data for div INT test", dataProviderClass = StaticProvider.class, threadPoolSize = 4)
Отсутствуют тесты на:
1. @Parameters
2. retryAnalyzer
3. Double.NaN
4. Double.NEGATIVE_INFINITY
5. Double.POSITIVE_INFINITY

2023-06-30 20:25 UTC, kislayao commented on src/test/java/CalculatorTest_Div_Int.java
> +    @Test (groups = "smoke", dataProvider = "Data for div INT test", dataProviderClass = StaticProvider.class, threadPoolSize = 4)
Double.POSITIVE_INFINITY test was in the CalculatorTest_Div_Double class
All other tests were added also to the same class

Also I've question:
I've tried to run div_test_INT.xml which has tests for CalculatorTest_Div_Int class and all the test failed with NullPointerException
But when I run tests in the CalculatorTest_Div_Int class itself everything is OK
It looks like calculator object becomes unreachable when I run test via div_test_INT.xml
Could you give me a hint what can be wrong?

2023-07-03 20:06 UTC, wildpioneer commented on src/test/java/CalculatorTest_Div_Int.java
> +    @Test (groups = "smoke", dataProvider = "Data for div INT test", dataProviderClass = StaticProvider.class, threadPoolSize = 4)
To find out what the issue with NPE - you have to review TestNG lesson. I explained the usage of Before/After annotations.

2023-07-03 20:07 UTC, wildpioneer commented
Проверено

2023-07-03 20:07 UTC, closed without merging